export const SET_ORDER_BY = 'SET_ORDER_BY';
export const SET_ORDER = 'SET_ORDER';
export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';
